
<!DOCTYPE html>
<html lang="ca">
<head>
	<title>trav agency -ERROR</title>
	<meta charset="utf-8">
	<link rel="stylesheet" type="text/css" href="{APP_W}/application/public/themes/{THEME}/css/estil.css">
	<!-- jQuery library (served from Google) -->
        
        
</head>
<body>

	<div id="container">
		<div id="header">
                    <div id="barra">
                    <div id="capsa">    
                    <h1 style="margin-bottom:0;"><a href="{APP_W}/">Travel Agency- Error</a></h1>
		</div>
                </div>
                </div>
            
        </div>
</body>
</html>