
	<div id="container">
		<div id="content" >
                    <div id="slide">
                        <ul class="bxslider">
                            <li><img src="{APP_W}/application/public/themes/{THEME}/img/pic1.jpg" /></li>
                            <li><img src="{APP_W}/application/public/themes/{THEME}/img/pic2.jpg" /></li>
                            <li><img src="{APP_W}/application/public/themes/{THEME}/img/pic3.jpg" /></li>
                            <li><img src="{APP_W}/application/public/themes/{THEME}/img/pic4.jpg" /></li>
                        </ul>
                    </div>
		
                <div id="output">
                    <div class="buscador">
                        <div class="tabs">
                            <ul>
                                <li class="selected"><a href="#hotels">Hotels</a></li>
                                <li><a href="#vols">Vols</a></li>
                                <li><a href="#cotxes">Cotxes</a></li>
                            </ul>
                        <div class="tab hotels">
                            <h3> HOTELS</h3>
                            <form id="formhotel" method="post" action="{APP_W}/index/buscaHotel">
                                
                                <label>Data entrada <input type="text" id="datepicker" name="entrada"></label>
                                </br>
                                <input type="submit" value="Busca">
                            </form>
                        </div>
                        <div class="tab vols">
                           <h3> VOLS </h3>
                            <input type="submit" value="Busca">
                       </div>
                        <div class="tab cotxes">
                            <h3>COTXES</h3>
                             <input type="submit" value="Busca">
                        </div>
                        
                     </div>
                    
                </div>
                </div>
        </div>   
        </div>

        