

	

		
	<div id="container">	
		<div class="menu">
			<ul>
                       	    <li><a href="#">Home</a></li>
                            <li><a href="#">Editar</a></li>
                            <li><a href="#"></a></li>
                            
			</ul>
		</div>

		<div id="content" >
                    
		
                <div id="output">
                    <div id="formreg">
                        <form class="reg" action="{APP_W}/user/register" method="post">
                            <h3>Registre</h3>
                            <label>Nom<input type="text" name="nom" required="true" placeholder="nom" /></label>
                            <label>Cognoms<input type="text" name="cognoms" required="true" placeholder="cognoms" /></label>
                            <label>Email<input type="text" name="email" required="true" placeholder="email" /></label>
                            <label>Password<input type="password" name="password" required="true" placeholder="password" /></label>
                            <label>Repetiu password<input type="text" name="repassword" required="true" placeholder="password" /></label>
                            <input type="submit" id="botReg" value="Registra" />
                        </form>

                    </div>
                </div>
                </div>

        </div>